---
- hosts: wildfly-controller2
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.100 wildfly-domain.4labs.example wildfly-domain
        - 172.16.0.101 wildfly-controller1.4labs.example wildfly-controller1
        - 172.16.0.102 wildfly-controller2.4labs.example wildfly-controller2
        - 172.16.0.103 devops-node.4labs.example devops-node
        - 172.16.0.104 monitoring-node.4labs.example monitoring-node

    - name: Remove linhas que começam com 127.0.1.1 ou 127.0.2.1 no /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.[12].1'
        state: absent

    - name: Desativa o gerenciamento de DNS pelo NetworkManager
      copy:
        dest: /etc/NetworkManager/conf.d/dns.conf
        content: |
          [main]
          dns=none

    - name: Reinicia o NetworkManager para aplicar mudanças
      service:
        name: NetworkManager
        state: restarted

    - name: Instalar dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Instalar policycoreutils-python-utils
      dnf:
        name: policycoreutils-python-utils
        state: present

    - name: Adicionar repositório do Docker
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Instalar pacotes do Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Habilitar e iniciar o serviço Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Adicionar usuário 'suporte' ao grupo Docker
      user:
        name: suporte
        groups: docker
        append: yes
          
