global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.16.0.104:9100']

#  - job_name: 'wildfly-domain'
#    static_configs:
#      - targets: ['172.16.0.101:9100']

# - job_name: 'wildfly-controller1'
#    static_configs:
#      - targets: ['172.16.0.101:9100']

#  - job_name: 'wildfly-controller2'
#    static_configs:
#      - targets: ['172.16.0.102:9100']

#  - job_name: 'standalone-metrics-controller1'
#    metrics_path: '/metrics'
#    static_configs:
#      - targets: ['172.16.0.101:9990']
#    fallback_scrape_protocol: "PrometheusText0.0.4"

#  - job_name: 'standalone-metrics-controller2'
#    metrics_path: '/metrics'
#    static_configs:
#      - targets: ['172.16.0.102:9990']
#    fallback_scrape_protocol: "PrometheusText0.0.4"
