services:
  gitea-db:
    image: postgres:13
    container_name: gitea-db
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_password
      POSTGRES_DB: gitea
    volumes:
      - ./gitea-db-data:/var/lib/postgresql/data
    networks:
      - devops-network

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea_password
      GITEA__webhook__ALLOWED_HOST_LIST: "172.16.0.103,localhost,127.0.0.1"
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./gitea-data:/data  # Pasta local para dados do Gitea
    depends_on:
      - gitea-db
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
